name: Assign Milestone

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  assign-milestone:
    runs-on: windows 
    
    steps:
      - name: Assign Milestone
        uses: OctoLinker/assign-milestone@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          milestone-name: 'Your Milestone Name'
